name: Main Pipeline

on:
  push:
    branches: [master]

jobs:
  call_greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  
      - uses: ./github/workflows/greet.yml
        with:
          name: "Dhanraj Desai"
#./.github/workflows/greet_call.yml