name: Greeting
on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
jobs:
  greet_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, ${{ github.event.inputs.name }}!"