name: Main Pipeline

on:
  push:
    branches: [master]

jobs:
  call_greeting:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world"
      - run: date  
      
#./.github/workflows/greet_call.yml