name: Main Pipeline

on:
  push:
    branches: [master]

jobs:
  call_greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: /.github/workflows/greet.yml
        with:
          name: "GitHub Actions User"
#./.github/workflows/greet_call.yml